[wordpress]
172.17.177.40 ansible_user=vagrant ansible_ssh_private_key_file="/Users/bmota/Desktop/DevOps/Project-blog/.vagrant/machines/wordpress/virtualbox/private_key"

[mysql]
172.17.177.41 ansible_user=vagrant ansible_ssh_private_key_file="/Users/bmota/Desktop/DevOps/Project-blog/.vagrant/machines/mysql/virtualbox/private_key"
