###Este playbook roda no Ubuntu 22.04###
- hosts: mysql
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:

    - name: 'Atualizando pacotes'
      shell: 'sudo apt-get update'

    - name: 'Instalando pacotes'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: 
        - mysql-server-8.0
        - python3-mysqldb

    - name: 'Criando o Banco de dados'
      mysql_db:
        name: wordpress_db
        #login_user: root
        state: present
      become: yes

    - name: 'Criando usuario de MySQL'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present
        host: "{{ item }}"
      become: yes
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '35.89.139.246' #ip do wordpress server

    - name: 'Configurando mysql para aceitar conexão remota'
      copy:
        src: '/Users/bmota/Desktop/DevOps/Project-blog/mysqld.cnf'
        dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      become: yes
      notify:
        - restart mysql

- hosts: wordpress
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Atualizando pacotes'
      shell: 'sudo apt-get update'

    - name: 'Instalando pacotes'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: 
        - php8.1
        - apache2
        - libapache2-mod-php8.1
        - php8.1-gd
        #- libssh2-php7.2
        - php-ssh2
        #- php7.2-mcrypt
        - php8.1-mysql

    - name: 'Baixando o Wordpress'
      get_url:
        url: 'http://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: 'Descompactando Wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/html/
        remote_src: yes
      become: yes
    
    - copy:
        src: '/var/www/html/wordpress/wp-config-sample.php'
        dest: '/var/www/html/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configurando o wp-config com as entradas do mysql'
      replace:
        path: '/var/www/html/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '12345'}
        - { regex: 'localhost', value: '35.87.205.89'} #ip do mysql server
      become: yes  

    - name: 'Configurando o apache para servir o Worpress'
      copy:
        src: '/Users/bmota/Desktop/DevOps/Project-blog/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes  
      notify:
        - restart apache        
    